### ISSUE TITLE
mkDep with other inputs doesn't merge recursively

### ISSUE THREAD

**Issue by phanirithvij** [matt1432/nixos-configs#1]
I was going through your code trying to adapt it (mainly for pr-tracker module) but looked at the flakegen flake.in.nix

take for example
```nix
nix-on-droid = mkDep {
		...
        inputs.home-manager.follows = "home-manager";
};
```

If you look at the `nix flake metadata` or in the flake.lock you can see there is two home-manager instances. `home-manager_2` exists because in the flake.nix the home-manager follows statement is missing.

Seems in `mkDep` the `//` won't work with recursive merges.

I found this https://stackoverflow.com/a/54505212/8608146 but don't know how I can get the `lib` from nixpkgs when it is one of the inputs itself. This is all getting too complicated to just avoid copy pasting one ` inputs.nixpkgs.follows = "nixpkgs";` line.

I'm not critisising your config just an observation. I too am trying to modularise/refactor too much in my config.

**Comment by matt1432** [comment]
Oh yes you're right! Thank you for telling me, never would've realised lmao. I can't imagine if i had gotten a bug because of that.

**Comment by phanirithvij** [comment]
Let me know in case you do fix it. I personally have opted to not using genflake/flakegen.

**Comment by matt1432** [comment]
Fixed! You can see my latest commit. I think that should cover it since there are no other attribute sets under each input?

**Comment by phanirithvij** [comment]
Ok I'll check it out, you may close the issue.
